DROP TABLE timetable;
DROP TABLE teacher;
DROP TABLE room;
DROP TABLE absence;
DROP TABLE subject;
DROP TABLE grade;
DROP TABLE homework;
DROP TABLE message;
DROP TABLE class;
DROP TABLE times;

CREATE TABLE timetable (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE teacher (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE room (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE absence (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE subject (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE grade (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE homework (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE message (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE class (
    id INT AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE times (
    id INT AUTO_INCREMENT PRIMARY KEY,
);


